apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}
  labels:
    app: {{ template "service.name" . }}
    chart: {{ template "service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.environment }}
  annotations:
    fmp.register-consul: "false"
    fmp.service-postfix: ""
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http

  selector:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
    environment: {{ .Values.environment }}
